name: marlin_auto_build
description: 'Continuous automatic builds of the Marlin 3d-printer firmware'
author: 'zisismaras'
branding:
  icon: 'code'
  color: 'green'

on:
  push:
    paths:
      - 'builds/**'
  schedule:
    - cron:  '30 3 * * *'

jobs:
  create_builds:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        token: ${{ github.token }}
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install -U platformio
    - run: npm install
    - run: npm run build
    - run: node ./lib/runner.js --color
      env:
        GITHUB_TOKEN: ${{ github.token }}
