name: marlin_auto_build
description: 'Continuous automatic builds of the Marlin 3d-printer firmware'
author: 'zisismaras'

branding:
  icon: 'code'
  color: 'green'

secrets:
  token:
    default: ${{ github.token }}
inputs:
  repository:
    default: ${{ github.repository }}
  actor:
    default: ${{ github.actor }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2.3.4
      with:
        token: ${{ secrets.token }}
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install -U platformio
    - run: npm install
    - run: npm run build
    - run: node ./lib/runner.js --color
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
        GITHUB_ACTOR: ${{ inputs.actor }}
